version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
