version: '3'

services:
  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  registry_data:
    driver: local

